[package]
name = "crypto"
version = "0.1.0"
edition = "2021"


authors = ["Pritam Prasad <mail@pritamprasad.com>"]
description = "ecc crypto based interfaces to js"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2"